### PR TITLE
don't end error to sentry or attempt resending when 410 received

### PR DESCRIPTION
**Pull request by wheresrhys**
This will end this constant stream of errors in sentry https://app.getsentry.com/nextftcom/ft-next-myft-email-generator/group/94328312/ (Have already spoke to Dani about sending us 410s instead of 400)

### CODE REVIEW

**Comment by phamann** [comment]
Is there any way we could push these users uuid's in a queue/store so we can process them. I.e. disable their email prefs in the api or delete them?

**Comment by phamann** [comment]
:+1: Other than comment

**Comment by wheresrhys** [comment]
Yes absolutely, but outside remit of bug duty and I guess low priority for you currently. backlog it

**Comment by phamann** [comment]
Have added to backlog: https://trello.com/c/HGmLfATE

**Comment by geek-caroline** [comment]
I'll try and get the end point returning a 410 rather than a 400 asap.

**Pull request merged**
